### ISSUE TITLE
Duplicating widgets on full-width mode

### ISSUE THREAD

**Issue by B3QL** [duilio/pelican-octopress-theme#10]
When you go to a single post page and enlarge content by clicking on arrow. The widgets are duplicated.
![screenshot](https://f.cloud.github.com/assets/3527244/268012/1f52bfea-8ef8-11e2-8978-871e04f44479.png)

**Comment by mstreuhofer** [comment]
seeing as the PR #37 fixes this i guess this issue can be closed.
