### ISSUE TITLE
Empty ATOM feed

### ISSUE THREAD

**Issue by ttyS0** [duilio/pelican-octopress-theme#23]
I use RSS instead of ATOM feeds, and kept getting a duplicate empty ATOM feed in the navigation bar. In templates/_includes/navigation.html there is an "{% if FEED_RSS %}" block, but not a corresponding "{% if FEED_ATOM %}". Adding it removed the duplicate feed icon.

---

```
@@ -1,5 +1,7 @@
 <ul class="subscription" data-subscription="rss">
+  {% if FEED_ATOM %}
   <li><a href="{{ FEED_DOMAIN }}/{{ FEED_ATOM }}" rel="subscribe-rss">RSS</a></li>
+  {% endif %}
   {% if FEED_RSS %}
   <li><a href="{{ FEED_DOMAIN }}/{{ FEED_RSS }}" rel="subscribe-rss">RSS</a></li>
   {% endif %}
```

**Comment by mstreuhofer** [comment]
this issue is fixed by now and can be closed.
